{% set version = "0.5.1" %}

package:
  name: visualpic
  version: {{ version }}

source:
  url: https://github.com/AngelFP/VisualPIC/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5ecbe92fac5ea5148d901438ab5d734ce467653becbf0cf9f64baa8a86577f14

build:
  number: 0
  noarch: python
  entry_points:
      - vpic = visualpic.cli.vpic:vpic
      - vpic3d = visualpic.cli.vpic3d:vpic3d
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - aptools
    - h5py
    - matplotlib-base
    - numpy
    - openpmd-viewer
    - python >=3.7
    - pyvista
    - pyqt
    - scipy
    - tqdm
    - vtk

test:
  imports:
    - visualpic

about:
  home: https://github.com/AngelFP/VisualPIC/tree/dev/examples
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Data Visualization for Particle-in-Cell Codes

  description: |
    VisualPIC - Data Visualization for Particle-in-Cell Codes.
  dev_url: https://github.com/AngelFP/VisualPIC

extra:
  recipe-maintainers:
    - AngelFP
    - ax3l
